### PR TITLE
our attempt to fix it.

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Comment by heinrichreimer** [comment]
I'll let @Andrew-Quebe merge this.

**Comment by pjebs** [comment]
can you update the tag please. I don't think the new change can be used by gradle until you tag.

**Comment by Andrew-Quebe** [comment]
I'm not in charge of maven releases. @paolorotolo

**Comment by Andrew-Quebe** [comment]
Yeah, give me a sec. Just realized this was my library, so I can actually do that. Disregard my other comment.

**Comment by Andrew-Quebe** [comment]
@pjebs I will update you here when I fix maven.

**Comment by Andrew-Quebe** [comment]
@pjebs Follow the instructions here: https://github.com/apl-devs/Permissions-Helper/releases/tag/v1.1

The readme has also been updated.

**Pull request merged**
